// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYF40cVZe2NhPvLMugngDjbpuiuXkqGw',
    appId: '1:948847214685:web:ecf2f530511dcf6c3a8db4',
    messagingSenderId: '948847214685',
    projectId: 'auto-30725',
    authDomain: 'auto-30725.firebaseapp.com',
    storageBucket: 'auto-30725.appspot.com',
    measurementId: 'G-BZ5Y47YHSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3gLAOb30xeVeBPA7ShKN_p7MGirYKw4',
    appId: '1:948847214685:android:c06f0dedebc8cbdf3a8db4',
    messagingSenderId: '948847214685',
    projectId: 'auto-30725',
    storageBucket: 'auto-30725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6pNtCZfWa7XeXXpibQQlV4ogOYs52MWQ',
    appId: '1:948847214685:ios:702131136c2a77ff3a8db4',
    messagingSenderId: '948847214685',
    projectId: 'auto-30725',
    storageBucket: 'auto-30725.appspot.com',
    iosBundleId: 'com.example.autoAura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6pNtCZfWa7XeXXpibQQlV4ogOYs52MWQ',
    appId: '1:948847214685:ios:702131136c2a77ff3a8db4',
    messagingSenderId: '948847214685',
    projectId: 'auto-30725',
    storageBucket: 'auto-30725.appspot.com',
    iosBundleId: 'com.example.autoAura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYF40cVZe2NhPvLMugngDjbpuiuXkqGw',
    appId: '1:948847214685:web:eba7617b82c3a9773a8db4',
    messagingSenderId: '948847214685',
    projectId: 'auto-30725',
    authDomain: 'auto-30725.firebaseapp.com',
    storageBucket: 'auto-30725.appspot.com',
    measurementId: 'G-CYBV6GQX41',
  );
}
